### PR TITLE
Dont inline css from style link element in body when pedantic filter enabled. This is to maintain w3c validation of page. Bug fix #1153

### LINKED ISSUE #1153: pedantic filter should prevent inlining CSS into the body
Automatic CSS inlining leaves `<style>` tag inside `<body>`, making the pages invalid.

### PR DESCRIPTION
**Pull request by ashishk-1**
When pedantic filter is enabled, style link element in body is not inlined. When move_css_to_head filter is enabled, inlining is allowed because css is moved to head which is valid as per w3c standard.

### CODE REVIEW

File: net/instaweb/rewriter/css_inline_filter.cc [hunk 1]
```diff
@@ -111,11 +112,22 @@ void CssInlineFilter::StartDocumentImpl() {
...
+}
+
 void CssInlineFilter::EndElementImpl(HtmlElement* element) {
   // Don't inline if the CSS element is under <noscript>.
   if (noscript_element() != NULL) {
     return;
   }
+
+  if (element->keyword() == HtmlName::kBody) {
+    in_body_ = false;
```
Comment (oschaaf) [inline net/instaweb/rewriter/css_inline_filter.cc]: Do you see any direct benefit in setting `in_body_` to `false` again here?
I can see that doing this ensures that the value keeps reflecting the name (`in_body_`), but if that is all, maybe we should rename `in_body_` to `inlining_not_pedantically_spec_` and remove this code?

**Review by oschaaf — COMMENTED** [review]
Thanks! Mostly looks good to me, one question.

File: net/instaweb/rewriter/css_inline_filter.cc (hunk 1 above)
Comment (ashishk-1) [reply net/instaweb/rewriter/css_inline_filter.cc]: In case <body> element comes before <head>, so thought of making in_body_ to false in EndElementImpl(). But actually for w3c compatibility, this original structure itself will not be compatible. So we can remove this.  
I can also rename this flag as you mentioned.

Comment (ashishk-1) [reply net/instaweb/rewriter/css_inline_filter.cc]: In above post, I meant if body element comes before head element.

(formatting of angulat brackets removed element name)

File: pagespeed/system/system_tests/inline_css_link_element_in_body.sh [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+# AND pedantic filter is enabled
+$WGET -O $WGET_OUTPUT $TEST_ROOT/inline_style_link_in_body/inlining_style_link_body.html\
+?PageSpeedFilters=pedantic,inline_css
+# checking for no inlining of css
+check [ $(grep -c "href=\"style.css\"" $WGET_OUTPUT) = 1 ]
+
+# css inlined and moved to head
+URL="http://localhost:8080/mod_pagespeed_test/inline_style_link_in_body/inlining_style_link_body.html?PageSpeedFilters=pedantic,inline_css,move_css_to_head"
+# checking contents of inlined css
+# check [ $(grep -c ".foo" $WGET_OUTPUT) = 1 ]
```
Comment (oschaaf) [inline pagespeed/system/system_tests/inline_css_link_element_in_body.sh]: stray comment?

File: pagespeed/system/system_tests/inline_css_link_element_in_body.sh [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+
+# css not inlined because style link element in body
+# AND pedantic filter is enabled
+$WGET -O $WGET_OUTPUT $TEST_ROOT/inline_style_link_in_body/inlining_style_link_body.html\
+?PageSpeedFilters=pedantic,inline_css
+# checking for no inlining of css
+check [ $(grep -c "href=\"style.css\"" $WGET_OUTPUT) = 1 ]
+
+# css inlined and moved to head
+URL="http://localhost:8080/mod_pagespeed_test/inline_style_link_in_body/inlining_style_link_body.html?PageSpeedFilters=pedantic,inline_css,move_css_to_head"
```
Comment (oschaaf) [inline pagespeed/system/system_tests/inline_css_link_element_in_body.sh]: Use `$TEST_ROOT` instead of  `localhost:8080`?

**Review by oschaaf — CHANGES_REQUESTED** [review]
Two small requests for the system test, but other then that this looks good to me.

**Review by oschaaf — APPROVED** [review]

**Comment by oschaaf** [comment]
@jmarantz are you ok with this being merged?

File: net/instaweb/rewriter/css_inline_filter.cc [hunk 4]
```diff
@@ -97,7 +97,8 @@ class CssInlineFilter::Context : public InlineRewriteContext {
 CssInlineFilter::CssInlineFilter(RewriteDriver* driver)
     : CommonFilter(driver),
       id_(RewriteOptions::kCssInlineId),
-      size_threshold_bytes_(driver->options()->css_inline_max_bytes()) {
+      size_threshold_bytes_(driver->options()->css_inline_max_bytes()),
+      inlining_not_pedantically_spec_(false) {
```
Comment (jmarantz) [inline net/instaweb/rewriter/css_inline_filter.cc]: This is actually a document-state bit, which I didn't realize until I saw where it was spec.  So you need to init it in StartDocumentImpl, as the same CssInlineFilter class instance can be re-used for multiple documents (we recycle drivers for compatible configurations).

Also I think I would call the bit has_pedantic_inline_violations_.

File: net/instaweb/rewriter/css_inline_filter.cc [hunk 5]
```diff
@@ -111,11 +112,21 @@ void CssInlineFilter::StartDocumentImpl() {
 
 CssInlineFilter::~CssInlineFilter() {}
 
+void CssInlineFilter::StartElementImpl(HtmlElement* element) {
+
+  // w3c incompatible when css inlining in body with pedantic enabled
+  if (element->keyword() == HtmlName::kBody &&
+      driver()->options()->Enabled(RewriteOptions::kPedantic)) {
+    inlining_not_pedantically_spec_ = true;
```
Comment (jmarantz) [inline net/instaweb/rewriter/css_inline_filter.cc]: I don't understand what's being tracked here.  This function gets called for every document element when inlining is on, and there will always be a 'body' element.  I think this is tracking whether we are inside the 'body' in which case it might be less confusing to call this variable in_body_ (contradicting my suggestion above).

File: net/instaweb/rewriter/css_inline_filter.cc [hunk 6]
```diff
@@ -138,6 +149,18 @@ void CssInlineFilter::EndElementImpl(HtmlElement* element) {
           "CSS not inlined because media does not match screen", element);
       return;
     }
+
+    // Dont inline if style <link> element is in html body AND
+    // move_css_to_head is not enabled.
+    // This is to maintain w3c validation since style element is
+    // not recommended in html body. Issue fix #1153.
+    if (inlining_not_pedantically_spec_ &&
```
Comment (jmarantz) [inline net/instaweb/rewriter/css_inline_filter.cc]: shouldn't this be ANDed with Enabled(RewriteOptions::kPedantic)?

**Comment by jmarantz** [comment]
I left some comments.  I think this has some corner-cases that need to be
addressed:
  - behavior with 'pedantic' off
  - behavior when the same RewriteDriver object processes a second document

File: net/instaweb/rewriter/css_inline_filter.cc (hunk 5 above)
Comment (ashishk-1) [reply net/instaweb/rewriter/css_inline_filter.cc]: I am tracking whether we are in body with pedantic filter enabled. I can change this variable to in_body_ and will shift pedantic filter enable check to EndElementImpl() function, so that it will become less confusing. I will also init variable in StartDocumentImpl.

File: net/instaweb/rewriter/css_inline_filter.cc (hunk 6 above)
Comment (ashishk-1) [reply net/instaweb/rewriter/css_inline_filter.cc]: I ANDed pedantic filter enable check in StartElementImpl where I was checking whether we are in body. 
Now I am changing the variable to in_body_ and will also move pedantic filter enable check in endElementImpl().

**Comment by ashishk-1** [comment]
>   - behavior with 'pedantic' off

when pedantic filter is off, inlining_not_pedantically_spec_(now changing to in_body_) will be false always and will inline the css even if style link element is there in html body. I will add one more unit and system test for this.

> - behavior when the same RewriteDriver object processes a second document

I will add the test of multiple page loading in single test.

**Comment by oschaaf** [comment]
any objections against merging this?

File: net/instaweb/rewriter/css_inline_filter.cc [hunk 7]
```diff
@@ -107,15 +107,24 @@ void CssInlineFilter::InitStats(Statistics* statistics) {
 }
 
 void CssInlineFilter::StartDocumentImpl() {
+    in_body_ = false;
```
Comment (jmarantz) [inline net/instaweb/rewriter/css_inline_filter.cc:111]: also init this in the constructor (I know this is redundant but it just seems cleaner to make sure it doesn't ever have garbage in it).  I think in practice this won't matter.

**Review by jmarantz — APPROVED** [review]
