### PR TITLE
rewrite images in elements with parent/child. Bug fix #1308

### LINKED ISSUE #1308: Allow UrlValuedAttribute:image on elements with children
Hi,
I opened a new issue that is related by issue #1297 
That is by using the syntax :

ModPagespeedUrlValuedAttribute li data-thumb image

the image ended up duplicate in the html just like what Mr. @oschaaf  said in the original issue post

Thank you very much

### PR DESCRIPTION
**Pull request by ashishk-1**
Bug fix for issue https://github.com/pagespeed/mod_pagespeed/issues/1308 .
Added system test to verify fix. System test contains image rewriting in parent/child elements with flush.

### CODE REVIEW

File: pagespeed/system/system_tests/image_rewrite_with_flush.sh [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+# Testing image rewrites with parent node as well as child node
+# Also involved php flush routine
+start_test Image rewrite with flush.
+HOST_NAME="http://image-rewrite-with-flush.example.com"
+URL="http://image-rewrite-with-flush.example.com/mod_pagespeed_test/image_rewrite_with_flush/image_rewrite_with_flush.php"
+RESPONSE_OUT=$(http_proxy=$SECONDARY_HOSTNAME $WGET -O - $URL)
```
Comment (oschaaf) [inline pagespeed/system/system_tests/image_rewrite_with_flush.sh]: Instead of two requests (you may need more before you get the optimized images), it's better to use something like this here:
```
http_proxy=$SECONDARY_HOSTNAME fetch_until -save "$URL" 'fgrep -c .pagespeed.ic' 2
```

**Review by oschaaf — CHANGES_REQUESTED** [review]

File: install/mod_pagespeed_test/image_rewrite_with_flush/image_rewrite_with_flush.php [hunk 2]
```diff
@@ -0,0 +1,18 @@
+<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
+<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
+<head>
+  <title>Title of the document </title>
+</head>
+<body>
+<ul>
+  <li data-thumb="a.jpg">
```
Comment (jmarantz) [inline install/mod_pagespeed_test/image_rewrite_with_flush/image_rewrite_with_flush.php:8]: This system test is great; thanks for doing this!

But I'd also consider writing a unit test.  See https://github.com/pagespeed/mod_pagespeed/blob/master/net/instaweb/rewriter/css_filter_test.cc#L2297 for a CSS test with a flush in an inline style element as a model.  

Copy that and modify it according to your needs into https://github.com/pagespeed/mod_pagespeed/blob/master/net/instaweb/rewriter/image_rewrite_filter_test.cc

If you have any questions please don't hesitate to ask.

**Review by oschaaf — APPROVED** [review]

File: install/mod_pagespeed_test/image_rewrite_with_flush/image_rewrite_with_flush.php (hunk 2 above)
Comment (ashishk-1) [reply install/mod_pagespeed_test/image_rewrite_with_flush/image_rewrite_with_flush.php:8]: Sure. I will work on adding unit test also.

**Comment by oschaaf** [comment]
@ashishk-1 unit tests looks good to me, thanks!

**Comment by oschaaf** [comment]
LGTM,  @jmarantz are you OK with merging this?

File: net/instaweb/rewriter/image_rewrite_filter_test.cc [hunk 3]
```diff
@@ -1357,6 +1357,28 @@ TEST_F(ImageRewriteTest, ImgSrcSetWithCacheExtender) {
...
+  SetupWriter();
+  rewrite_driver()->StartParse(kTestDomain);
+  rewrite_driver()->ParseText("<html><body><ul><li data-thumb='Puzzle.jpg'>");
+  // Flush in middle of parent and child element
+  rewrite_driver()->Flush();
+  rewrite_driver()->ParseText("<img src='Puzzle.jpg'/></li></ul></body></html>");
+  rewrite_driver()->FinishParse();
+
+  // Check output with optimized parent, child image nodes
+  EXPECT_EQ("<html><body><ul><li data-thumb='xPuzzle.jpg.pagespeed.ic.0.jpg'>"
```
Comment (jmarantz) [inline net/instaweb/rewriter/image_rewrite_filter_test.cc]: EXPECT_STREQ

**Review by jmarantz — APPROVED** [review]
nice!  one tiny nit.

**Comment by oschaaf** [comment]
Merged - thanks @ashishk-1 !
